- .github/workflows/main.yml
[actions/cache@2](https://github.com/actions/cache/releases/tag/v2.0.0) has been released and comes with some useful updates.
> Upgrade actions/cache to v2

- package.json
- src/annotator.ts
- src/index.ts
- src/is.test.ts
- src/is.ts
- src/mapDeep.ts
- src/pathstringifier.ts
- src/plainer.ts
- src/transformer.ts
- src/types.ts
- yarn.lock
It turns out that `@sindresorhus/is` is actually quite big! Right now it accounts for 64% of our [bundle size](https://bundlephobia.com/result?p=superjson@1.0.1). This is because it provides much more functionality than we actually need–we only use a handful of `is.whatever` functions. I’ve therefore written a custom type-checking util which should be much more lightweight. This also means we can brag about having zero external dependencies 😄.
> Implement custom type checking

- package.json
- src/annotator.ts
- src/index.test.ts
- src/iteratorutils.ts
- src/pathstringifier.ts
- src/plainer.ts
- src/transformer.ts
- yarn.lock
Since Maps are forced to have a uniform key type (see https://github.com/blitz-js/superjson/pull/6#issuecomment-661693147), it's bonkers to include it for every single key.
This commit replaces the `map` type with `map:number`, `map:string`, `map:bigint` and `map:boolean` to save some space.
> Transmit map key type as part of the value type

- src/accessDeep.test.ts
- src/accessDeep.ts
- src/index.test.ts
- src/plainer.test.ts
- src/plainer.ts
- src/transformer.ts
- src/types.ts
Closes #33, #35 
While we had been trying to fit Map's semantics into JSON's object, the solution had been in front of us all along: It's impossible!
That's why `new Map(...)` takes a list of pairs instead of an object.
This PR suggests to also use a list of pairs to serialize `Map`, which allows us to distinguish different objects from one another and also support non-primitive values.
This PR may be a bit hard to comprehend, so please go forward and ask all the questions you like ^^
> Serialize `Map` using a list of pairs

- benchmark.js
- src/class-registry.test.ts
- src/class-registry.ts
- src/index.test.ts
- src/index.ts
- src/transformer.ts
- src/types.ts
Closes #34 
Implements revival of ES6 classes by attaching the original prototypes during revival. It requires registering all neccessary classes using `SuperJSON.registerClass(...)`.
In the future, this could be done automatically in a compile-step (Which poses it's own issues, e.g. figuring out which classes are actually used and which classes to bundle therefore, but would make it opaque to Blitz users).
> Revive classes

- src/index.ts
Somehow this export got removed from the previous release which is a breaking change.
> Fix export of `serialize`

- src/index.test.ts
- src/pathtree.ts
Closes #58.
Due to how the prefix detection in `PathTree` worked, serialising and object with paths `yee` and `yee2` didn't work as expected. This PR fixes that.
> Fix bug with existing prefixes in PathTree

- src/is.ts
This PR relates to #68.
Performance should increase 15 to 20%.
> Less generic type checks

- package.json
- src/annotator.ts
- src/custom-transformer-registry.ts
- src/double-indexed-kv.ts
- src/index.test.ts
- src/index.ts
- src/registry.test.ts
- src/registry.ts
- src/transformer.ts
- yarn.lock
Related to #69 
This PR allows users to supply their own, custom serialisers.
For MongoDB's ObjectIDs, this can be used like the following:
```ts
import SuperJSON from "superjson";
import { ObjectID } from "mongodb";
// this needs to be executed both on client and server
SuperJSON.registerCustom<ObjectID, string>(
{
isApplicable: (v): v is ObjectID => v instanceof ObjectID,
serialize: v => v.toHexString(),
deserialize: v => new ObjectID(v),
},
'objectid'
);
// ...
SuperJSON.serialise({ a: new ObjectID(), ... })
```
> Add support for custom serialisers

- README.md
- src/index.test.ts
- src/is.ts
- src/transformer.ts
SuperJSON now natively supports serialising the `Error` type.
Closes #74
> Add support for serialising Errors

- src/error-props.ts
- src/index.test.ts
- src/index.ts
- src/transformer.ts
This adds `SuperJSON.allowErrorProps(...)`, which can be used to register non-standard error props to be transformed.
See #91
> allowErrorProps(...) (#91)

- src/index.test.ts
- src/index.ts
causes issues in next if trying to serialize `[]`
(try using `serialize([])` in `getStaticProps()`)
> fix - don't set meta if empty

- src/registry.test.ts
- src/registry.ts
> Only check for ambiguous classes in development

- .github/workflows/main.yml
- src/index.test.ts
- src/transformer.ts
> Fix #62 (Again)

- package.json
- src/registry.test.ts
- src/registry.ts
- yarn.lock
> Move "Ambiguous Class" to debug() call

- package.json
- tsconfig.json
> build: use tsc output code in both cjs and esm formats 

- README.md
Closes https://github.com/blitz-js/babel-plugin-superjson-next/issues/107
> fix: babel-plugin-superjson-next needs to be a prod dependency

- README.md
Closes: #157 
I made [next-superjson-plugin](https://github.com/orionmiz/next-superjson-plugin) (swc plugin for Next.js)
So added simple instructions to use SuperJSON in the recent version of Next.js
> docs: add a section of swc plugin for Next.js

- src/is.test.ts
- src/is.ts
Before:
```
toy example x 89,736 ops/sec ±0.91% (97 runs sampled)
user graph x 21,863 ops/sec ±0.37% (90 runs sampled)
deep nested x 21.42 ops/sec ±1.54% (40 runs sampled)
```
After:
```
toy example x 94,658 ops/sec ±1.14% (92 runs sampled)
user graph x 23,187 ops/sec ±0.38% (96 runs sampled)
deep nested x 22.04 ops/sec ±1.26% (41 runs sampled)
```
Also, `isPlainObject` would return true on `Object.prototype` which is now fixed and added to the tests.
> More performant check of isPlainObject

- src/class-registry.ts
- src/custom-transformer-registry.ts
- src/error-props.ts
- src/index.test.ts
- src/index.ts
- src/plainer.spec.ts
- src/plainer.ts
- src/symbol-registry.ts
- src/transformer.ts
this allows the creation of individual superjson instances, so there can be multiple different configurations.
it keeps the global instance in place for backwards compatibility, and b/c most users will be fine with one global config.
> refactor: allow individual superjson instances (closes #87)

- src/registry.test.ts
- src/registry.ts
closes https://github.com/blitz-js/superjson/issues/208
> fix: remove "already registered" warning, which triggered too many false positives

- README.md
Hi all,
I see there is a mutual support between libraries related to this topic.
I would kinly ask to accept my mutual reference as well.
Thank you
> docs: add reference to next-json in prior art section

- src/accessDeep.ts
- src/index.test.ts
Fairly straight-forward fix plus test case for an issue I noticed when deserializing complex structures with maps and referential equality.
> Fix applying referential equality inside maps and sets

- src/accessDeep.ts
When using typescript 5 in a project using superjson the build fails with the following error:
```text
./node_modules/superjson/src/accessDeep.ts:102:5
Type error: Element implicitly has an 'any' type because expression of type 'string | number' can't be used to index type 'any[] | { [key: string]: any; }'.
No index signature with a parameter of type 'string' was found on type 'any[] | { [key: string]: any; }'.
100 | 
101 |   if (isArray(parent) || isPlainObject(parent)) {
> 102 |     parent[lastKey] = mapper(parent[lastKey]);
|     ^
103 |   }
104 | 
105 |   if (isSet(parent)) {
```
This change fixes this error.
> Fix compilation error with typescript 5

- README.md
Hopefully it'll save someone else some time
> Fix example date type in README

- src/is.ts
This fixes https://github.com/blitz-js/superjson/issues/242
> fix: isPlainObject type check with edge runtime

- src/index.test.ts
- src/plainer.ts
Closes #245
- Short-circuit result of the walker on already-seen objects
- Will make outputs less noisy
- Should make superjson faster too
---
```sh
yarn test --watch --testNamePattern "#245" --testPathPattern index
```
> fix: referential equalities should ignore child nodes

- src/index.ts
"Fixes" https://github.com/blitz-js/superjson/pull/247#issuecomment-1637631294
```ts
import { SuperJSON } from "superjson"
const superjson = new SuperJSON();
```
now works. default import still broken though
> fix: TypeError: SuperJSON is not a constructor

- src/index.test.ts
- src/index.ts
- src/plainer.ts
We found a bug with dedupe option.
I'm sorry for this repro, it's awful and huge and bloated. Haven't narrowed it down more, but AFAICT, the results of these should be equal but they aren't.
The problem shows in the diff between non-deduped and deduped; some values stay as `null` after deserializing the deduped one.
> bug repro with dedupe=true

- package.json
If I'm not mistaking `"main": "./dist/index.js"` would have no effect when `"exports"` is defined. Right now it's required to resolve the module within a monorepo react-native app.
> add "main" to package.json

- tsconfig.json
Updating the compile target, see https://github.com/blitz-js/superjson/issues/268#issuecomment-1779063042.
@all-contributors please add @peterbud for bug
> fix: target es2020

- src/transformer.test.ts
- src/transformer.ts
This pull request introduces a new test case and improves error messaging in the `SuperJSON` deserialization process. The changes enhance the developer experience by providing more descriptive error messages and ensuring the robustness of the code.
* [`src/transformer.ts`](diffhunk://#diff-df7446068188621a3fa66e02d4e5c9081902f1bb2cd9092e06c59271978257d3L278-R278): Updated the error message to include the name of the unknown class being deserialized, making it easier to identify the issue.
* [`src/transformer.test.ts`](diffhunk://#diff-035655380b270a040027fd0c4ca50f1a2f05731e6654bc177d9cd00b1c1e3c5fR1-R28): Added a new test case to verify that an appropriate error is thrown when attempting to deserialize an unregistered class, ensuring that the error message includes missing class name.
> Add unknown class name to deserialization error

- src/index.test.ts
- src/index.ts
- src/pathstringifier.test.ts
- src/pathstringifier.ts
- src/plainer.ts
- src/types.ts
Closes https://github.com/flightcontrolhq/superjson/issues/310
There's a bug in the path escaping logic where meta was applied to the wrong values. This PR fixes the escape bug. It also introduces a version tag to toggle the path escaping when deserializing. This ensures backwards compatibility for SuperJSON results that were created on a version with the bug.
> fix: input escape mapping
