flightcontrolhq/superjson

src/annotator.ts
src/index.test.ts
src/iteratorutils.ts
src/plainer.ts
tsconfig.json

Fix prod crash hidden by --downLevelIteration

---

README.md
src/index.ts

Closes #41 
Good catch @flybayer! :D

Make return type of `parse` user-configurable

---

LICENSE
package.json

As discussed with @merelinguist, I‘ll be listed as author and @flybayer and @merelinguist will be listed as contributors in `package.json`.

Update author / contributors

---

src/transformer.ts

Moving transformation and untransformation logic closer together into so-called „transform rules“ increases cohesion and locality of change, but it comes at an increased cognitive complexity. What do y‘all think?

Refactor Transformer to make rules more cohesive

---

src/index.test.ts
src/types.ts

👋🏻 
Related to https://github.com/blitz-js/superjson/issues/48
Let me know if any changes needed :)

Fix deserialize should accept `undefined`

---

src/annotator.ts
src/index.test.ts
src/transformer.ts

Fix crash when BigInt isn't available

---

src/index.test.ts

test: adding test for unknown type

---

src/index.test.ts
src/is.test.ts
src/transformer.ts

#83 
:warning: I honestly don't know when one would ever use negative zero and I'd rather see the serialization throw errors on `NaN`/`-0`/`Infinity`/`-Infinity`

Negative zero support

---

package.json
src/custom-transformer-registry.ts
src/pathtree.ts
src/plainer.ts
src/transformer.ts
src/util.ts
tsconfig.json
yarn.lock

Remove lodash

---

package.json
src/index.test.ts
yarn.lock

This makes all updates proposed in #99, including [manual adjustment](https://github.com/formium/tsdx/issues/926#issuecomment-751936109) to accomodate for https://github.com/formium/tsdx/issues/926.

Update all deps

---

src/class-registry.ts
src/index.test.ts
src/index.ts
src/transformer.ts

#104: per-class allowProps

---

src/transformer.ts

Re https://github.com/blitz-js/superjson/issues/116#issuecomment-773996564

Mention minifier issues in Error

---

package.json
yarn.lock

Not neccessary as of #120, but forgot to remove it.

Remove dependency "debug"

---

package.json
yarn.lock

Reverts blitz-js/superjson#121

Revert "Remove dependency "debug""

---

package.json
src/index.test.ts
src/index.ts
yarn.lock

Closes https://github.com/blitz-js/babel-plugin-superjson-next/issues/63

Don't mutate deserialized object

---

src/index.test.ts
src/is.test.ts
src/is.ts

support serializing objects without prototype

---

README.md
package.json
src/index.test.ts
yarn.lock

Add a recipe for Decimal.js

---

README.md

Small fix to the readme for correctness ;)

parse() returns the original value

---

src/index.ts

fix(src/index): export `stringify` function

---

package.json
src/index.ts
yarn.lock

started out with `rfdc` but found that it was unmaintained. 
After some more searching, I found copy-anything. Which is also even smaller!
should help make the footprint smaller :)
`yarn test` passes
`yarn build` finished successfully
solves #182
EDIT: I used a different computer than my regular one, so my commits are unverified lol

refactor: change lodash.clonedeep to copy-anything

---

package.json
src/registry.test.ts
src/registry.ts
yarn.lock

This PR reduces bundle size by dropping the "debug" dependency.

drop "debug" dependency

---

src/index.ts

export registerCustom etc

---

src/index.ts

fix: export statics as named exports

---

README.md

```
code ERESOLVE
ERESOLVE unable to resolve dependency tree
npm ERR!
While resolving: admin@1.0.0
Found: next@12.3.4
node_modules/next
next@"^12.3.3" from the root project
npm ERR!
Could not resolve dependency:
peer next@"^13" from next-superjson-plugin@0.5.7
node_modules/next-superjson-plugin
next-superjson-plugin@"*" from the root project
```

chore: Update required NextJS version in readme

---

src/index.ts

- Fixes https://github.com/blitz-js/superjson/issues/271

Export SuperJSONResult type

---

src/index.ts

export SuperJSONValue
